package country

type CountryDataType struct {
	Name       string `json:"name"`
	Code       string `json:"code"`
	DailCode   string `json:"dail_code"`
	TimeOffset int    `json:"time_offset"`
}

var IndianStates = []string{
	"Andhra Pradesh",
	"Arunachal Pradesh",
	"Assam",
	"Bihar",
	"Chhattisgarh",
	"Goa",
	"Gujarat",
	"Haryana",
	"Himachal Pradesh",
	"Jharkhand",
	"Karnataka",
	"Kerala",
	"Madhya Pradesh",
	"Maharashtra",
	"Manipur",
	"Meghalaya",
	"Mizoram",
	"Nagaland",
	"Odisha",
	"Punjab",
	"Rajasthan",
	"Sikkim",
	"Tamil Nadu",
	"Telangana",
	"Tripura",
	"Uttar Pradesh",
	"Uttarakhand",
	"West Bengal",
}

var AllCountryData = []CountryDataType{
	{
		Name:       "Afghanistan",
		Code:       "AF",
		DailCode:   "+93",
		TimeOffset: 270,
	},
	{
		Name:       "Albania",
		Code:       "AL",
		DailCode:   "+355",
		TimeOffset: 120,
	},
	{
		Name:       "Algeria",
		Code:       "DZ",
		DailCode:   "+213",
		TimeOffset: 60,
	},
	{
		Name:       "Andorra",
		Code:       "AD",
		DailCode:   "+376",
		TimeOffset: 120,
	},
	{
		Name:       "Angola",
		Code:       "AO",
		DailCode:   "+244",
		TimeOffset: 60,
	},
	{
		Name:       "Antigua and Barbuda",
		Code:       "AG",
		DailCode:   "+1-268",
		TimeOffset: -240,
	},
	{
		Name:       "Argentina",
		Code:       "AR",
		DailCode:   "+54",
		TimeOffset: -180,
	},
	{
		Name:       "Armenia",
		Code:       "AM",
		DailCode:   "+374",
		TimeOffset: 240,
	},
	{
		Name:       "Australia",
		Code:       "AU",
		DailCode:   "+61",
		TimeOffset: 600,
	},
	{
		Name:       "Austria",
		Code:       "AT",
		DailCode:   "+43",
		TimeOffset: 120,
	},
	{
		Name:       "Azerbaijan",
		Code:       "AZ",
		DailCode:   "+994",
		TimeOffset: 240,
	},
	{
		Name:       "Bahamas",
		Code:       "BS",
		DailCode:   "+1-242",
		TimeOffset: -240,
	},
	{
		Name:       "Bahrain",
		Code:       "BH",
		DailCode:   "+973",
		TimeOffset: 180,
	},
	{
		Name:       "Bangladesh",
		Code:       "BD",
		DailCode:   "+880",
		TimeOffset: 360,
	},
	{
		Name:       "Barbados",
		Code:       "BB",
		DailCode:   "+1-246",
		TimeOffset: -240,
	},
	{
		Name:       "Belarus",
		Code:       "BY",
		DailCode:   "+375",
		TimeOffset: 180,
	},
	{
		Name:       "Belgium",
		Code:       "BE",
		DailCode:   "+32",
		TimeOffset: 120,
	},
	{
		Name:       "Belize",
		Code:       "BZ",
		DailCode:   "+501",
		TimeOffset: -360,
	},
	{
		Name:       "Benin",
		Code:       "BJ",
		DailCode:   "+229",
		TimeOffset: 60,
	},
	{
		Name:       "Bhutan",
		Code:       "BT",
		DailCode:   "+975",
		TimeOffset: 360,
	},
	{
		Name:       "Bolivia",
		Code:       "BO",
		DailCode:   "+591",
		TimeOffset: -240,
	},
	{
		Name:       "Bosnia and Herzegovina",
		Code:       "BA",
		DailCode:   "+387",
		TimeOffset: 120,
	},
	{
		Name:       "Botswana",
		Code:       "BW",
		DailCode:   "+267",
		TimeOffset: 120,
	},
	{
		Name:       "Brazil",
		Code:       "BR",
		DailCode:   "+55",
		TimeOffset: -180,
	},
	{
		Name:       "Brunei",
		Code:       "BN",
		DailCode:   "+673",
		TimeOffset: 480,
	},
	{
		Name:       "Bulgaria",
		Code:       "BG",
		DailCode:   "+359",
		TimeOffset: 180,
	},
	{
		Name:       "Burkina Faso",
		Code:       "BF",
		DailCode:   "+226",
		TimeOffset: 0,
	},
	{
		Name:       "Burundi",
		Code:       "BI",
		DailCode:   "+257",
		TimeOffset: 120,
	},
	{
		Name:       "Cabo Verde",
		Code:       "CV",
		DailCode:   "+238",
		TimeOffset: -60,
	},
	{
		Name:       "Cambodia",
		Code:       "KH",
		DailCode:   "+855",
		TimeOffset: 420,
	},
	{
		Name:       "Cameroon",
		Code:       "CM",
		DailCode:   "+237",
		TimeOffset: 60,
	},
	{
		Name:       "Canada",
		Code:       "CA",
		DailCode:   "+1",
		TimeOffset: -240,
	},
	{
		Name:       "Central African Republic",
		Code:       "CF",
		DailCode:   "+236",
		TimeOffset: 60,
	},
	{
		Name:       "Chad",
		Code:       "TD",
		DailCode:   "+235",
		TimeOffset: 60,
	},
	{
		Name:       "Chile",
		Code:       "CL",
		DailCode:   "+56",
		TimeOffset: -240,
	},
	{
		Name:       "China",
		Code:       "CN",
		DailCode:   "+86",
		TimeOffset: 480,
	},
	{
		Name:       "Colombia",
		Code:       "CO",
		DailCode:   "+57",
		TimeOffset: -300,
	},
	{
		Name:       "Comoros",
		Code:       "KM",
		DailCode:   "+269",
		TimeOffset: 180,
	},
	{
		Name:       "Congo",
		Code:       "CG",
		DailCode:   "+242",
		TimeOffset: 60,
	},
	{
		Name:       "Costa Rica",
		Code:       "CR",
		DailCode:   "+506",
		TimeOffset: -360,
	},
	{
		Name:       "Côte d'Ivoire",
		Code:       "CI",
		DailCode:   "+225",
		TimeOffset: 0,
	},
	{
		Name:       "Croatia",
		Code:       "HR",
		DailCode:   "+385",
		TimeOffset: 120,
	},
	{
		Name:       "Cuba",
		Code:       "CU",
		DailCode:   "+53",
		TimeOffset: -240,
	},
	{
		Name:       "Cyprus",
		Code:       "CY",
		DailCode:   "+357",
		TimeOffset: 120,
	},
	{
		Name:       "Czech Republic",
		Code:       "CZ",
		DailCode:   "+420",
		TimeOffset: 120,
	},
	{
		Name:       "Democratic Republic of the Congo",
		Code:       "CD",
		DailCode:   "+243",
		TimeOffset: 60,
	},
	{
		Name:       "Denmark",
		Code:       "DK",
		DailCode:   "+45",
		TimeOffset: 120,
	},
	{
		Name:       "Djibouti",
		Code:       "DJ",
		DailCode:   "+253",
		TimeOffset: 180,
	},
	{
		Name:       "Dominica",
		Code:       "DM",
		DailCode:   "+1-767",
		TimeOffset: -240,
	},
	{
		Name:       "Dominican Republic",
		Code:       "DO",
		DailCode:   "+1-809, +1-829, +1-849",
		TimeOffset: -240,
	},
	{
		Name:       "Ecuador",
		Code:       "EC",
		DailCode:   "+593",
		TimeOffset: -300,
	},
	{
		Name:       "Egypt",
		Code:       "EG",
		DailCode:   "+20",
		TimeOffset: 120,
	},
	{
		Name:       "El Salvador",
		Code:       "SV",
		DailCode:   "+503",
		TimeOffset: -360,
	},
	{
		Name:       "Equatorial Guinea",
		Code:       "GQ",
		DailCode:   "+240",
		TimeOffset: 60,
	},
	{
		Name:       "Eritrea",
		Code:       "ER",
		DailCode:   "+291",
		TimeOffset: 180,
	},
	{
		Name:       "Estonia",
		Code:       "EE",
		DailCode:   "+372",
		TimeOffset: 180,
	},
	{
		Name:       "Eswatini",
		Code:       "SZ",
		DailCode:   "+268",
		TimeOffset: 120,
	},
	{
		Name:       "Ethiopia",
		Code:       "ET",
		DailCode:   "+251",
		TimeOffset: 180,
	},
	{
		Name:       "Fiji",
		Code:       "FJ",
		DailCode:   "+679",
		TimeOffset: 720,
	},
	{
		Name:       "Finland",
		Code:       "FI",
		DailCode:   "+358",
		TimeOffset: 180,
	},
	{
		Name:       "France",
		Code:       "FR",
		DailCode:   "+33",
		TimeOffset: 120,
	},
	{
		Name:       "Gabon",
		Code:       "GA",
		DailCode:   "+241",
		TimeOffset: 60,
	},
	{
		Name:       "Gambia",
		Code:       "GM",
		DailCode:   "+220",
		TimeOffset: 0,
	},
	{
		Name:       "Georgia",
		Code:       "GE",
		DailCode:   "+995",
		TimeOffset: 240,
	},
	{
		Name:       "Germany",
		Code:       "DE",
		DailCode:   "+49",
		TimeOffset: 120,
	},
	{
		Name:       "Ghana",
		Code:       "GH",
		DailCode:   "+233",
		TimeOffset: 0,
	},
	{
		Name:       "Greece",
		Code:       "GR",
		DailCode:   "+30",
		TimeOffset: 180,
	},
	{
		Name:       "Grenada",
		Code:       "GD",
		DailCode:   "+1-473",
		TimeOffset: -240,
	},
	{
		Name:       "Guatemala",
		Code:       "GT",
		DailCode:   "+502",
		TimeOffset: -360,
	},
	{
		Name:       "Guinea",
		Code:       "GN",
		DailCode:   "+224",
		TimeOffset: 0,
	},
	{
		Name:       "Guinea-Bissau",
		Code:       "GW",
		DailCode:   "+245",
		TimeOffset: 0,
	},
	{
		Name:       "Guyana",
		Code:       "GY",
		DailCode:   "+592",
		TimeOffset: -240,
	},
	{
		Name:       "Haiti",
		Code:       "HT",
		DailCode:   "+509",
		TimeOffset: -240,
	},
	{
		Name:       "Honduras",
		Code:       "HN",
		DailCode:   "+504",
		TimeOffset: -360,
	},
	{
		Name:       "Hungary",
		Code:       "HU",
		DailCode:   "+36",
		TimeOffset: 120,
	},
	{
		Name:       "Iceland",
		Code:       "IS",
		DailCode:   "+354",
		TimeOffset: 0,
	},
	{
		Name:       "India",
		Code:       "IN",
		DailCode:   "+91",
		TimeOffset: 330,
	},
	{
		Name:       "Indonesia",
		Code:       "ID",
		DailCode:   "+62",
		TimeOffset: 420,
	},
	{
		Name:       "Iran",
		Code:       "IR",
		DailCode:   "+98",
		TimeOffset: 270,
	},
	{
		Name:       "Iraq",
		Code:       "IQ",
		DailCode:   "+964",
		TimeOffset: 180,
	},
	{
		Name:       "Ireland",
		Code:       "IE",
		DailCode:   "+353",
		TimeOffset: 60,
	},
	{
		Name:       "Israel",
		Code:       "IL",
		DailCode:   "+972",
		TimeOffset: 180,
	},
	{
		Name:       "Italy",
		Code:       "IT",
		DailCode:   "+39",
		TimeOffset: 120,
	},
	{
		Name:       "Jamaica",
		Code:       "JM",
		DailCode:   "+1-876",
		TimeOffset: -300,
	},
	{
		Name:       "Japan",
		Code:       "JP",
		DailCode:   "+81",
		TimeOffset: 540,
	},
	{
		Name:       "Jordan",
		Code:       "JO",
		DailCode:   "+962",
		TimeOffset: 180,
	},
	{
		Name:       "Kazakhstan",
		Code:       "KZ",
		DailCode:   "+7",
		TimeOffset: 360,
	},
	{
		Name:       "Kenya",
		Code:       "KE",
		DailCode:   "+254",
		TimeOffset: 180,
	},
	{
		Name:       "Kiribati",
		Code:       "KI",
		DailCode:   "+686",
		TimeOffset: 720,
	},
	{
		Name:       "Korea, North",
		Code:       "KP",
		DailCode:   "+850",
		TimeOffset: 510,
	},
	{
		Name:       "Korea, South",
		Code:       "KR",
		DailCode:   "+82",
		TimeOffset: 540,
	},
	{
		Name:       "Kosovo",
		Code:       "XK",
		DailCode:   "+383",
		TimeOffset: 120,
	},
	{
		Name:       "Kuwait",
		Code:       "KW",
		DailCode:   "+965",
		TimeOffset: 180,
	},
	{
		Name:       "Kyrgyzstan",
		Code:       "KG",
		DailCode:   "+996",
		TimeOffset: 360,
	},
	{
		Name:       "Laos",
		Code:       "LA",
		DailCode:   "+856",
		TimeOffset: 420,
	},
	{
		Name:       "Latvia",
		Code:       "LV",
		DailCode:   "+371",
		TimeOffset: 180,
	},
	{
		Name:       "Lebanon",
		Code:       "LB",
		DailCode:   "+961",
		TimeOffset: 180,
	},
	{
		Name:       "Lesotho",
		Code:       "LS",
		DailCode:   "+266",
		TimeOffset: 120,
	},
	{
		Name:       "Liberia",
		Code:       "LR",
		DailCode:   "+231",
		TimeOffset: 0,
	},
	{
		Name:       "Libya",
		Code:       "LY",
		DailCode:   "+218",
		TimeOffset: 120,
	},
	{
		Name:       "Liechtenstein",
		Code:       "LI",
		DailCode:   "+423",
		TimeOffset: 120,
	},
	{
		Name:       "Lithuania",
		Code:       "LT",
		DailCode:   "+370",
		TimeOffset: 180,
	},
	{
		Name:       "Luxembourg",
		Code:       "LU",
		DailCode:   "+352",
		TimeOffset: 120,
	},
	{
		Name:       "Madagascar",
		Code:       "MG",
		DailCode:   "+261",
		TimeOffset: 180,
	},
	{
		Name:       "Malawi",
		Code:       "MW",
		DailCode:   "+265",
		TimeOffset: 120,
	},
	{
		Name:       "Malaysia",
		Code:       "MY",
		DailCode:   "+60",
		TimeOffset: 480,
	},
	{
		Name:       "Maldives",
		Code:       "MV",
		DailCode:   "+960",
		TimeOffset: 300,
	},
	{
		Name:       "Mali",
		Code:       "ML",
		DailCode:   "+223",
		TimeOffset: 0,
	},
	{
		Name:       "Malta",
		Code:       "MT",
		DailCode:   "+356",
		TimeOffset: 120,
	},
	{
		Name:       "Marshall Islands",
		Code:       "MH",
		DailCode:   "+692",
		TimeOffset: 720,
	},
	{
		Name:       "Mauritania",
		Code:       "MR",
		DailCode:   "+222",
		TimeOffset: 0,
	},
	{
		Name:       "Mauritius",
		Code:       "MU",
		DailCode:   "+230",
		TimeOffset: 240,
	},
	{
		Name:       "Mexico",
		Code:       "MX",
		DailCode:   "+52",
		TimeOffset: -300,
	},
	{
		Name:       "Micronesia",
		Code:       "FM",
		DailCode:   "+691",
		TimeOffset: 660,
	},
	{
		Name:       "Moldova",
		Code:       "MD",
		DailCode:   "+373",
		TimeOffset: 180,
	},
	{
		Name:       "Monaco",
		Code:       "MC",
		DailCode:   "+377",
		TimeOffset: 120,
	},
	{
		Name:       "Mongolia",
		Code:       "MN",
		DailCode:   "+976",
		TimeOffset: 480,
	},
	{
		Name:       "Montenegro",
		Code:       "ME",
		DailCode:   "+382",
		TimeOffset: 120,
	},
	{
		Name:       "Morocco",
		Code:       "MA",
		DailCode:   "+212",
		TimeOffset: 60,
	},
	{
		Name:       "Mozambique",
		Code:       "MZ",
		DailCode:   "+258",
		TimeOffset: 120,
	},
	{
		Name:       "Myanmar",
		Code:       "MM",
		DailCode:   "+95",
		TimeOffset: 390,
	},
	{
		Name:       "Namibia",
		Code:       "NA",
		DailCode:   "+264",
		TimeOffset: 120,
	},
	{
		Name:       "Nauru",
		Code:       "NR",
		DailCode:   "+674",
		TimeOffset: 720,
	},
	{
		Name:       "Nepal",
		Code:       "NP",
		DailCode:   "+977",
		TimeOffset: 345,
	},
	{
		Name:       "Netherlands",
		Code:       "NL",
		DailCode:   "+31",
		TimeOffset: 120,
	},
	{
		Name:       "New Zealand",
		Code:       "NZ",
		DailCode:   "+64",
		TimeOffset: 720,
	},
	{
		Name:       "Nicaragua",
		Code:       "NI",
		DailCode:   "+505",
		TimeOffset: -360,
	},
	{
		Name:       "Niger",
		Code:       "NE",
		DailCode:   "+227",
		TimeOffset: 60,
	},
	{
		Name:       "Nigeria",
		Code:       "NG",
		DailCode:   "+234",
		TimeOffset: 60,
	},
	{
		Name:       "North Macedonia",
		Code:       "MK",
		DailCode:   "+389",
		TimeOffset: 120,
	},
	{
		Name:       "Norway",
		Code:       "NO",
		DailCode:   "+47",
		TimeOffset: 120,
	},
	{
		Name:       "Oman",
		Code:       "OM",
		DailCode:   "+968",
		TimeOffset: 240,
	},
	{
		Name:       "Pakistan",
		Code:       "PK",
		DailCode:   "+92",
		TimeOffset: 300,
	},
	{
		Name:       "Palau",
		Code:       "PW",
		DailCode:   "+680",
		TimeOffset: 540,
	},
	{
		Name:       "Palestine",
		Code:       "PS",
		DailCode:   "+970",
		TimeOffset: 180,
	},
	{
		Name:       "Panama",
		Code:       "PA",
		DailCode:   "+507",
		TimeOffset: -300,
	},
	{
		Name:       "Papua New Guinea",
		Code:       "PG",
		DailCode:   "+675",
		TimeOffset: 600,
	},
	{
		Name:       "Paraguay",
		Code:       "PY",
		DailCode:   "+595",
		TimeOffset: -240,
	},
	{
		Name:       "Peru",
		Code:       "PE",
		DailCode:   "+51",
		TimeOffset: -300,
	},
	{
		Name:       "Philippines",
		Code:       "PH",
		DailCode:   "+63",
		TimeOffset: 480,
	},
	{
		Name:       "Poland",
		Code:       "PL",
		DailCode:   "+48",
		TimeOffset: 120,
	},
	{
		Name:       "Portugal",
		Code:       "PT",
		DailCode:   "+351",
		TimeOffset: 60,
	},
	{
		Name:       "Qatar",
		Code:       "QA",
		DailCode:   "+974",
		TimeOffset: 180,
	},
	{
		Name:       "Romania",
		Code:       "RO",
		DailCode:   "+40",
		TimeOffset: 180,
	},
	{
		Name:       "Russia",
		Code:       "RU",
		DailCode:   "+7",
		TimeOffset: 180,
	},
	{
		Name:       "Rwanda",
		Code:       "RW",
		DailCode:   "+250",
		TimeOffset: 120,
	},
	{
		Name:       "Saint Kitts and Nevis",
		Code:       "KN",
		DailCode:   "+1-869",
		TimeOffset: -240,
	},
	{
		Name:       "Saint Lucia",
		Code:       "LC",
		DailCode:   "+1-758",
		TimeOffset: -240,
	},
	{
		Name:       "Saint Vincent and the Grenadines",
		Code:       "VC",
		DailCode:   "+1-784",
		TimeOffset: -240,
	},
	{
		Name:       "Samoa",
		Code:       "WS",
		DailCode:   "+685",
		TimeOffset: 780,
	},
	{
		Name:       "San Marino",
		Code:       "SM",
		DailCode:   "+378",
		TimeOffset: 120,
	},
	{
		Name:       "Sao Tome and Principe",
		Code:       "ST",
		DailCode:   "+239",
		TimeOffset: 0,
	},
	{
		Name:       "Saudi Arabia",
		Code:       "SA",
		DailCode:   "+966",
		TimeOffset: 180,
	},
	{
		Name:       "Senegal",
		Code:       "SN",
		DailCode:   "+221",
		TimeOffset: 0,
	},
	{
		Name:       "Serbia",
		Code:       "RS",
		DailCode:   "+381",
		TimeOffset: 120,
	},
	{
		Name:       "Seychelles",
		Code:       "SC",
		DailCode:   "+248",
		TimeOffset: 240,
	},
	{
		Name:       "Sierra Leone",
		Code:       "SL",
		DailCode:   "+232",
		TimeOffset: 0,
	},
	{
		Name:       "Singapore",
		Code:       "SG",
		DailCode:   "+65",
		TimeOffset: 480,
	},
	{
		Name:       "Slovakia",
		Code:       "SK",
		DailCode:   "+421",
		TimeOffset: 120,
	},
	{
		Name:       "Slovenia",
		Code:       "SI",
		DailCode:   "+386",
		TimeOffset: 120,
	},
	{
		Name:       "Solomon Islands",
		Code:       "SB",
		DailCode:   "+677",
		TimeOffset: 660,
	},
	{
		Name:       "Somalia",
		Code:       "SO",
		DailCode:   "+252",
		TimeOffset: 180,
	},
	{
		Name:       "South Africa",
		Code:       "ZA",
		DailCode:   "+27",
		TimeOffset: 120,
	},
	{
		Name:       "South Sudan",
		Code:       "SS",
		DailCode:   "+211",
		TimeOffset: 180,
	},
	{
		Name:       "Spain",
		Code:       "ES",
		DailCode:   "+34",
		TimeOffset: 120,
	},
	{
		Name:       "Sri Lanka",
		Code:       "LK",
		DailCode:   "+94",
		TimeOffset: 330,
	},
	{
		Name:       "Sudan",
		Code:       "SD",
		DailCode:   "+249",
		TimeOffset: 180,
	},
	{
		Name:       "SuriName",
		Code:       "SR",
		DailCode:   "+597",
		TimeOffset: -180,
	},
	{
		Name:       "Sweden",
		Code:       "SE",
		DailCode:   "+46",
		TimeOffset: 120,
	},
	{
		Name:       "Switzerland",
		Code:       "CH",
		DailCode:   "+41",
		TimeOffset: 120,
	},
	{
		Name:       "Syria",
		Code:       "SY",
		DailCode:   "+963",
		TimeOffset: 180,
	},
	{
		Name:       "Taiwan",
		Code:       "TW",
		DailCode:   "+886",
		TimeOffset: 480,
	},
	{
		Name:       "Tajikistan",
		Code:       "TJ",
		DailCode:   "+992",
		TimeOffset: 300,
	},
	{
		Name:       "Tanzania",
		Code:       "TZ",
		DailCode:   "+255",
		TimeOffset: 180,
	},
	{
		Name:       "Thailand",
		Code:       "TH",
		DailCode:   "+66",
		TimeOffset: 420,
	},
	{
		Name:       "Timor-Leste",
		Code:       "TL",
		DailCode:   "+670",
		TimeOffset: 540,
	},
	{
		Name:       "Togo",
		Code:       "TG",
		DailCode:   "+228",
		TimeOffset: 0,
	},
	{
		Name:       "Tonga",
		Code:       "TO",
		DailCode:   "+676",
		TimeOffset: 780,
	},
	{
		Name:       "Trinidad and Tobago",
		Code:       "TT",
		DailCode:   "+1-868",
		TimeOffset: -240,
	},
	{
		Name:       "Tunisia",
		Code:       "TN",
		DailCode:   "+216",
		TimeOffset: 60,
	},
	{
		Name:       "Turkey",
		Code:       "TR",
		DailCode:   "+90",
		TimeOffset: 180,
	},
	{
		Name:       "Turkmenistan",
		Code:       "TM",
		DailCode:   "+993",
		TimeOffset: 300,
	},
	{
		Name:       "Tuvalu",
		Code:       "TV",
		DailCode:   "+688",
		TimeOffset: 720,
	},
	{
		Name:       "Uganda",
		Code:       "UG",
		DailCode:   "+256",
		TimeOffset: 180,
	},
	{
		Name:       "Ukraine",
		Code:       "UA",
		DailCode:   "+380",
		TimeOffset: 180,
	},
	{
		Name:       "United Arab Emirates",
		Code:       "AE",
		DailCode:   "+971",
		TimeOffset: 240,
	},
	{
		Name:       "United Kingdom",
		Code:       "GB",
		DailCode:   "+44",
		TimeOffset: 60,
	},
	{
		Name:       "United States",
		Code:       "US",
		DailCode:   "+1",
		TimeOffset: -240,
	},
	{
		Name:       "Uruguay",
		Code:       "UY",
		DailCode:   "+598",
		TimeOffset: -180,
	},
	{
		Name:       "Uzbekistan",
		Code:       "UZ",
		DailCode:   "+998",
		TimeOffset: 300,
	},
	{
		Name:       "Vanuatu",
		Code:       "VU",
		DailCode:   "+678",
		TimeOffset: 660,
	},
	{
		Name:       "Vatican City",
		Code:       "VA",
		DailCode:   "+379",
		TimeOffset: 120,
	},
	{
		Name:       "Venezuela",
		Code:       "VE",
		DailCode:   "+58",
		TimeOffset: -240,
	},
	{
		Name:       "Vietnam",
		Code:       "VN",
		DailCode:   "+84",
		TimeOffset: 420,
	},
	{
		Name:       "Yemen",
		Code:       "YE",
		DailCode:   "+967",
		TimeOffset: 180,
	},
	{
		Name:       "Zambia",
		Code:       "ZM",
		DailCode:   "+260",
		TimeOffset: 120,
	},
	{
		Name:       "Zimbabwe",
		Code:       "ZW",
		DailCode:   "+263",
		TimeOffset: 120,
	},
}
